export const translations = {
    pt: {
        profile: "Perfil",
        settings: "Configurações",
        personalization: "Personalização",
        languages: "Idiomas",
        app_settings: "configurações do app",
        back: "Voltar",
        auto_scroll: "Auto Rolagem",
        auto_scroll_sub: "Rolar automaticamente ao receber mensagens",
        collapse_code: "Colapsar Blocos de Código",
        collapse_code_sub: "Recolher blocos de código por padrão",
        my_nickname: "Meu Apelido",
        my_nickname_sub: "Como você gostaria que a AI te chamasse?",
        occupation: "Sua Ocupação (Opcional)",
        occupation_sub: "O que você faz? Isso ajuda a AI a dar respostas mais contextuais.",
        additional_instructions: "Instruções Adicionais",
        additional_instructions_sub: "O que você gostaria que a AI soubesse sobre você para fornecer respostas melhores?",
        ai_characteristics: "Características da AI",
        ai_characteristics_sub: "Adicione traços de personalidade ou comportamentos específicos para a AI.",
        traits_placeholder: "Ex: Sarcástico, Conciso, Engraçado...",
        your_conversations: "Suas Conversas",
        no_sessions: "Nenhuma conversa salva.",
        start_first_chat: "Iniciar uma nova conversa",
        loading: "Carregando...",
        new_chat: "Nova Conversa",
        type_placeholder: "Digite sua pergunta ou arraste um arquivo...",
        drop_file: "Solte seu arquivo aqui",
        reading_file: "Lendo arquivo...",
        processing: "Processando conhecimento...",
        interrupted: "Interrompido",
        error_processing: "Erro ao processar a solicitação",
        rename_chat: "Renomear conversa",
        rename_sub: "Dê um título claro a esta conversa",
        save: "Salvar",
        cancel: "Cancelar",
        show_more: "Mostrar mais",
        copy_msg: "Copiar mensagem",
        edit_msg: "Editar mensagem",
        lines: "linhas",
        line: "linha",
        seconds_ago: "há {n} segundo(s)",
        minutes_ago: "há {n} minuto(s)",
        hours_ago: "há {n} hora(s)",
        days_ago: "há {n} dia(s)",
        greeting_morning: "Bom dia",
        greeting_afternoon: "Boa tarde",
        greeting_evening: "Boa noite",
        select_language: "Selecionar Idioma",
        portuguese: "Português (Brasil)",
        english: "English",
        spanish: "Español (BETA)"
    },
    en: {
        profile: "Profile",
        settings: "Settings",
        personalization: "Personalization",
        languages: "Languages",
        app_settings: "app settings",
        back: "Back",
        auto_scroll: "Auto Scroll",
        auto_scroll_sub: "Automatically scroll when receiving messages",
        collapse_code: "Collapse Code Blocks",
        collapse_code_sub: "Collapse code blocks by default",
        my_nickname: "My Nickname",
        my_nickname_sub: "What would you like the AI to call you?",
        occupation: "Your Occupation (Optional)",
        occupation_sub: "What do you do? This helps the AI provide more contextual answers.",
        additional_instructions: "Additional Instructions",
        additional_instructions_sub: "What would you like the AI to know about you to provide better answers?",
        ai_characteristics: "AI Characteristics",
        ai_characteristics_sub: "Add personality traits or specific behaviors for the AI.",
        traits_placeholder: "e.g. Sarcastic, Concise, Funny...",
        your_conversations: "Your Conversations",
        no_sessions: "No saved conversations.",
        start_first_chat: "Start a new conversation",
        loading: "Loading...",
        new_chat: "New Chat",
        type_placeholder: "Type your question or drag a file...",
        drop_file: "Drop your file here",
        reading_file: "Reading file...",
        processing: "Processing knowledge...",
        interrupted: "Interrupted",
        error_processing: "Error processing request",
        rename_chat: "Rename conversation",
        rename_sub: "Give this conversation a clear title",
        save: "Save",
        cancel: "Cancel",
        show_more: "Show more",
        copy_msg: "Copy message",
        edit_msg: "Edit message",
        lines: "lines",
        line: "line",
        seconds_ago: "{n} second(s) ago",
        minutes_ago: "{n} minute(s) ago",
        hours_ago: "{n} hour(s) ago",
        days_ago: "{n} day(s) ago",
        greeting_morning: "Good morning",
        greeting_afternoon: "Good afternoon",
        greeting_evening: "Good evening",
        select_language: "Select Language",
        portuguese: "Português (Brasil)",
        english: "English",
        spanish: "Español (BETA)",
        // File size warning / truncation messages
        file_too_large: "File {name} exceeds size limit and will be truncated.",
        file_truncated: "File {name} was truncated to fit the prompt limits."
    },
    es: {
        profile: "Perfil",
        settings: "Ajustes",
        personalization: "Personalización",
        languages: "Idiomas",
        app_settings: "ajustes de la app",
        back: "Volver",
        auto_scroll: "Auto Desplazamiento",
        auto_scroll_sub: "Desplazar automáticamente al recibir mensajes",
        collapse_code: "Colapsar Bloques de Código",
        collapse_code_sub: "Colapsar bloques de código por defecto",
        my_nickname: "Mi Apodo",
        my_nickname_sub: "¿Cómo te gustaría que la IA te llamara?",
        occupation: "Tu Ocupación (Opcional)",
        occupation_sub: "¿A qué te dedicas? Esto ayuda a la IA a dar respuestas más contextuales.",
        additional_instructions: "Instrucciones Adicionales",
        additional_instructions_sub: "¿Qué te gustaría que la IA supiera sobre ti para dar mejores respuestas?",
        ai_characteristics: "Características de la IA",
        ai_characteristics_sub: "Añade rasgos de personalidad o comportamientos específicos para la IA.",
        traits_placeholder: "Ej: Sarcástico, Conciso, Divertido...",
        your_conversations: "Tus Conversaciones",
        no_sessions: "No hay conversaciones guardadas.",
        start_first_chat: "Iniciar una nueva conversación",
        loading: "Cargando...",
        new_chat: "Nueva Conversación",
        type_placeholder: "Escribe tu pregunta o arrastra un archivo...",
        drop_file: "Suelta tu archivo aquí",
        reading_file: "Leyendo archivo...",
        processing: "Procesando conocimiento...",
        interrupted: "Interrumpido",
        error_processing: "Error al procesar la solicitud",
        rename_chat: "Renombrar conversación",
        rename_sub: "Dale un título claro a esta conversación",
        save: "Guardar",
        cancel: "Cancelar",
        show_more: "Mostrar más",
        copy_msg: "Copiar mensaje",
        edit_msg: "Editar mensaje",
        lines: "líneas",
        line: "línea",
        seconds_ago: "hace {n} segundo(s)",
        minutes_ago: "hace {n} minuto(s)",
        hours_ago: "hace {n} hora(s)",
        days_ago: "hace {n} día(s)",
        greeting_morning: "Buenos días",
        greeting_afternoon: "Buenas tardes",
        greeting_evening: "Buenas noches",
        select_language: "Seleccionar Idioma",
        portuguese: "Português (Brasil)",
        english: "English",
        spanish: "Español",
        // File size warning / truncation messages
        file_too_large: "El archivo {name} excede el límite y será truncado.",
        file_truncated: "El archivo {name} fue truncado para ajustarse a los límites del prompt."
    }
};